// `.env.json` is generated by the `npm run build` command
import env from './.env.json';

export const environment = {
    appName: 'LUNZ+',
    production: true,
    version: env.npm_package_version,
    localeId: 'zh-CN',
    defaultLanguage: 'en-US',
    supportedLanguages: [
        'en-US',
        'fr-FR'
    ],
    authentication: {
        // oauth2 / usercenter
        type: 'usercenter',
        useServiceV1: true
    },
    odic: {
        config: {
            authority: 'http://{identity-server-domain}',
            client_id: '',
            redirect_uri: 'http://{domain}/authentication/callback',
            response_type: 'id_token token',
            scope: 'openid profile',
            post_logout_redirect_uri: 'http://{domain}'
        }
    },
    // Web Api
    serverUrl: '',
    appKey: '',
    withHeaders: false,
    // User Center
    userCenter: {
        serverUrl: '',
        appKey: '',
        authUri: ''
    },
    // Message Center
    msgCenter: {
        signalR: '',
        serverUrl: '',
        appKey: ''
    },
    // Data Center
    dataCenter: {
        serverUrl: '',
        appKey: ''
    },
    // Customer Center
    customerCenter: {
        serverUrl: '',
        appKey: '',
        authUri: ''
    }
};
