// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  appName: 'LUNZ+',
  production: false,
  hmr: true,
  version: env.npm_package_version + '-dev',
  localeId: 'zh-CN',
  haveTabs: false,
  serverUrl: '',
  defaultLanguage: 'zh-CN',
  supportedLanguages: ['en-US', 'fr-FR'],
  authentication: {
    // oauth2 / usercenter
    type: 'usercenter',
    useServiceV1: true
  },
  odic: {
    config: {
      authority: '',
      client_id: '',
      redirect_uri: '',
      response_type: '',
      scope: '',
      post_logout_redirect_uri: ''
    }
  },
  api: {
    default: 'v1',
    // WebAPI for V2 - Microservice
    v2: {
      baseUrl: ''
    },
    // WebAPI for V1
    v1: {
      baseUrl: '',
      appKey: '',
      withHeaders: true
    },
    // User Center
    userCenter: {
      baseUrl: '',
      appKey: '',
      authUri: ''
    },
    // Message Center
    messageCenter: {
      signalR: '',
      baseUrl: '',
      appKey: ''
    },
    // Data Center
    dataCenter: {
      baseUrl: '',
      appKey: ''
    },
    // Customer Center
    customerCenter: {
      baseUrl: '',
      appKey: ''
    }
  }
};

