// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  appName: 'LUNZ+',
  production: true,
  hmr: false,
  version: env.npm_package_version,
  localeId: 'zh-CN',
  defaultLanguage: 'zh-CN',
  supportedLanguages: ['en-US', 'fr-FR'],
  idle: true,
  freeTime: 5,  // 单位：分钟
  countdownTime: 20, // 单位：秒
  haveTabs: true,
  authentication: {
    // oauth2 / usercenter
    type: 'usercenter',
    useServiceV1: true
  },
  odic: {
    config: {
      authority: '',
      client_id: 'lunz-ui-dev',
      redirect_uri: '',
      response_type: 'id_token token',
      scope: 'openid profile lunz-sharp-template',
      post_logout_redirect_uri: ''
    }
  },
  api: {
    default: 'v1',
    // WebAPI for V2 - Microservice
    v2: {
      baseUrl: ''
    },
    // WebAPI for V1
    v1: {
      baseUrl: '',
      appKey: '',
      applicationId: '',
      withHeaders: true
    },
    // User Center
    userCenter: {
      baseUrl: '',
      appKey: '',
      authUri: '',
    },
    // Message Center
    messageCenter: {
      signalR: '',
      baseUrl: '',
      appKey: ''
    },
    // Data Center
    dataCenter: {
      baseUrl: '',
      appKey: ''
    },
    // Customer Center
    customerCenter: {
      baseUrl: '',
      appKey: ''
    }
  }
};
