site_name: LUNZ+
pages:
    - '简介': index.md
    - '快速开始': quick-start/quick-start.md
    - '开发环境': development-environment/development-environment.md
    - '开始 LUNZ+':
        - '开发流程': lunz/technological-process/technological-process.md
        - '获取源码，运行项目': lunz/step1/step1.md
        - '创建模块，配置路由': lunz/step2/step2.md
        - '创建服务': lunz/step3/step3.md
        - '创建订单列表组件': lunz/step4/step4.md
        - '创建新建/编辑订单组件': lunz/step5/step5.md
        - '发布': lunz/release/release.md
    - 'LUNZ+ 组件':
        - 'form表单': component/form/form.md
        - 'ngx-datatable数据列表展示': component/ngx-datatable/ngx-datatable.md
        - 'ngx-query查询过滤': component/ngx-query/ngx-query.md
        - '列表页脚复杂型（ngx-datatable-footer）': component/ngx-datatable-footer/ngx-datatable-footer.md
        - '列表页脚简单型（ngx-datatable-footer-simple）': component/ngx-datatable-footer-simple/ngx-datatable-footer-simple.md
        - '时间选择器': component/datepicker/datepicker.md
        - '表单验证器': component/validator/validator.md
        - 'Select选择器': component/select/select.md
        - 'Select2选择器': component/select2/select2.md
        - 'Dropdown下拉': component/dropdown/dropdown.md
        - '文件上传': component/upload/upload.md
        - '进度条': component/progress/progress.md
        - '车型选择': component/vehicle-select/vehicle-select.md
        - '树形结构': component/treeview/treeview.md
        - 'Tabs切换': component/tabs/tabs.md
        - 'Button按钮': component/button/button.md
        - 'Switch开关': component/switch/switch.md
        - 'Slider滑块': component/slider/slider.md
        - 'Badge标记': component/badge/badge.md
        - 'Card卡片': component/card/card.md
        - 'Tips提示': component/tips/tips.md
        - 'Counter计数器': component/counter/counter.md
        - 'Rate评分': component/rate/rate.md
        - 'Tag标签': component/tag/tag.md
        - 'Steps步骤条': component/steps/steps.md
        - 'Collapse折叠面板': component/collapse/collapse.md
        - '图表': component/chart/chart.md
        - 'Dialogs对话框': component/dialogs/dialogs.md
        - '按钮处理状态': component/angular2-ladda/angular2-ladda.md
        - 'Logger信息提示': component/logger/logger.md
        - '第三方组件库': component/third-party-components/third-party-components.md
        - '编写自定义组件': component/edit-component/edit-component.md
    - '部署':
        - 'Windows': deployment/deploy-windows.md
        - 'Linux': deployment/deploy-linux.md
        - '自动部署': deployment/auto-deploy.md
    - 'LUNZ+ 其它':
        - '环境变量': lunz-others/environment/environment.md
        - '配置路由': lunz-others/config-route/config-route.md
        - '常用命令': lunz-others/common-commands/common-commands.md
        - '管理样式和js文件': lunz-others/styles-js/styles-js.md
    - '构建私有项目': build-private-project/build-private-project.md
    - '强类型化API接口 (NSwagStudio)': strongly-typed-interface/strongly-typed-interface.md
    - '使用 Angular4':
        - '开始': angular4/angular4-index.md
        - 'Angular-cli': angular4/angular-cli/angular-cli.md
        - '应用模型': angular4/angular-application-model/angular-application-model.md
        - '应用目录': angular4/angular-catalog/angular-catalog.md
        - '模块': angular4/angular-model/angular-model.md
        - '组件': angular4/angular-component/angular-component.md
        - '服务': angular4/angular-service/angular-service.md
        - '指令': angular4/angular-directive/angular-directive.md
        - '管道': angular4/angular-pipe/angular-pipe.md
    - '从 AngularJs 转 Angular4': difference/difference.md
    - 'NPM 包管理': npm/npm-admin.md
    - '编码规范': coding-standards/coding-standards.md
    - '这个模板包含什么？': 
        - '这个模板包含什么？': template-include/template-include.md
        - 'angular': template-include/coding-guides/angular.md
        - 'backend-proxy': template-include/coding-guides/backend-proxy.md
        - 'corporate-proxy': template-include/coding-guides/corporate-proxy.md
        - 'e2e-tests': template-include/coding-guides/e2e-tests.md
        - 'html': template-include/coding-guides/html.md
        - 'i18n': template-include/coding-guides/i18n.md
        - 'routing': template-include/coding-guides/routing.md
        - 'sass': template-include/coding-guides/sass.md
        - 'typescript': template-include/coding-guides/typescript.md
        - 'unit-tests': template-include/coding-guides/unit-tests.md
        - 'updating': template-include/coding-guides/updating.md
theme:
  name: 'material'
  language: 'zh'
