site_name: LUNZ+
pages:
    - '简介': index.md
    - '应用程序':
        - '响应结果': application/response-result.md
        - '数据校验': application/validation.md
        
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'blue'